### ISSUE TITLE
Broken link in schema documentation

### ISSUE THREAD

**Issue by leksinteractive** [openmhealth/schemas#11]
Hi there,

I was looking at one of your schemas and noticed a broken link reference.

Schema: http://www.openmhealth.org/documentation/#/schema-docs/schema-library/schemas/omh_activity-name

Broken link: http://www.startwalkingnow.org/documents/PA_Intensity_table_2_1.pdf

That seems to be the only reference to that link and domain.

**Comment by scarini** [comment]
Hi Aleks and thank you for your comment. I had changed the reference on the headnote and overlooked the one in the schema itself. This has been fixed now.
