### ISSUE TITLE
Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@1177f25c

### ISSUE THREAD

**Issue by ascooper57** [openmhealth/schemas#3]
Same failure on Mac via command line and in Idea IntelliJ 

$ javac -version
javac 1.7.0_71

$ gradle --version
------------------------------------------------------------
Gradle 2.3
------------------------------------------------------------

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_71 (Oracle Corporation 24.71-b01)
OS:           Mac OS X 10.10.3 x86_64

$ gradle clean
Download https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.1/gradle-bintray-plugin-1.1.pom
Download https://jcenter.bintray.com/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.2.1/httpcomponents-client-4.2.1.pom
Download https://jcenter.bintray.com/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
Download https://jcenter.bintray.com/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.1/httpcore-4.2.1.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-core/4.2.1/httpcomponents-core-4.2.1.pom
Download https://jcenter.bintray.com/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.pom
Download https://jcenter.bintray.com/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.1/gradle-bintray-plugin-1.1.jar
Download https://jcenter.bintray.com/org/codehaus/groovy/modules/http-builder/http-builder/0.7.2/http-builder-0.7.2.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.jar
Download https://jcenter.bintray.com/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
Download https://jcenter.bintray.com/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.2.1/httpcore-4.2.1.jar
Download https://jcenter.bintray.com/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/schemas/java-schema-sdk/build.gradle' line: 83

* What went wrong:
A problem occurred evaluating project ':java-schema-sdk'.
> Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@1177f25c.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.848 secs

**Comment by ascooper57** [comment]
Should I use a solution as was implemented in an unrelated project?

https://github.com/embulk/embulk/commit/4019e0fd80ec997f5e411026dd5f87e70d2ae5ad

-        user = "$bintray_user"    // configure at your ~/.gradle/gradle.properties
-        key = "$bintray_api_key"  // configure at your ~/.gradle/gradle.properties
+        // write at your bintray user name and api key to ~/.gradle/gradle.properties file:
+        // bintray_user=frsyuki
+        // bintray_api_key=xxxxxxxxxxx
+        user = hasProperty('bintray_user') ? bintray_user : ''
+        key = hasProperty('bintray_api_key') ? bintray_api_key : ''

**Comment by ascooper57** [comment]
I worked around this issue by creating a gradle.properties file:

more ~/.gradle/gradle.properties
bintray_user=
bintray_api_key=

I still believe that the better solution is to enhance the build.gradle file with the ternary operators as show in the previous comment.

**Comment by emersonf** [comment]
Those properties are used to push [binaries](https://bintray.com/bintray/jcenter?filterByPkgName=omh-schema-sdk) to JCenter. I'll check if I can get Gradle to ignore those properties until the task to push is called. If not, I'll put in the ternaries. Thanks!

**Comment by emersonf** [comment]
Fixed with ternary operators, albeit slightly different ones since `hasProperty` wasn't working in the `bintray` definition.

**Comment by ascooper57** [comment]
I just did a git pull and I do see your edits. However:

 gradle clean install

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alan_cooper/Documents/GitHub/AperitasCloud/openmhealth/schemas/java-schema-sdk/build.gradle' line: 83

* What went wrong:
A problem occurred evaluating project ':java-schema-sdk'.
> Could not find property 'bintray_user' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@468036e3.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by emersonf** [comment]
Sigh, got a false positive on one of my tests. This should really fix it.

**Comment by ascooper57** [comment]
Hello,

Your latest edits work perfectly. Thank you for resolving this so quickly.

Alan Cooper
